apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-claim-100gi
spec:
  storageClassName: nfs-client 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi